### ISSUE TITLE
CSV indexing

### ISSUE THREAD

**Issue by ShihaoJing** [ShihaoJing/Pylasic#2]
So far, I believe there are 3 strategies to index datasets:

1. Index csv files directly.
2. Create Mapping and store csv files as a json text property.
3. Create Mapping and store csv files as a nested property.

For 1, each row will be indexed as a document.
For 2, it works. However, the query time becomes extremely slow for some query. Too long text might be the primary reason.
For 3, each nested json object will be flattened, as opposed to expected simple json object. If a csv file has 1000 columns, it will be flattened to 1000 properties. And, it crashed when I was trying to index data in this way (out of memory even if 15 GB memory allocated).

**Comment by ameliagalgon** [comment]
Add extra column to the csv file to contains the name of the original file that each document came from

**Comment by ShihaoJing** [comment]
I have a new idea about indexing.

Because some documents are too large (too many rows), we can cut it into slices. As I said, data will be stored as nested in each document.

I have done some experiments. It shows slices can speed up indexing and query time.

An example query can be like this:

```
GET baseindex2/_search
{
  "_source": "false", 
  "query": {
    "nested": {
      "path": "data",
      "query": {
        "bool": {
          "must": [
            { "match": { "data.HI_INC_COMP_2YR_TRANS_YR6_RT.keyword": "0.0278293135" }}, {"match": {
              "data.MD_INC_YR3_N.keyword": "1130"
            }}
          ]
        }
      }
    }
  }
}
```
Result:

```
{
  "took": 275,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 5,
    "max_score": 14.380009,
    "hits": [
      {
        "_index": "baseindex2",
        "_type": "basetype",
        "_id": "AVtjo1pOl2x6HBRMSjrQ",
        "_score": 14.380009,
        "_source": {}
      },
      {
        "_index": "baseindex2",
        "_type": "basetype",
        "_id": "AVtjo0czl2x6HBRMSjrP",
        "_score": 12.847793,
        "_source": {}
      },
      {
        "_index": "baseindex2",
        "_type": "basetype",
        "_id": "AVtjobRGl2x6HBRMSjq6",
        "_score": 12.484447,
        "_source": {}
      },
      {
        "_index": "baseindex2",
        "_type": "basetype",
        "_id": "AVtjoxwMl2x6HBRMSjrN",
        "_score": 12.484447,
        "_source": {}
      },
      {
        "_index": "baseindex2",
        "_type": "basetype",
        "_id": "AVtjozJsl2x6HBRMSjrO",
        "_score": 12.040104,
        "_source": {}
      }
    ]
  }
}
```
I have cut 'College Scorecard/Most-Recent-Cohorts-All-Data-Elements.csv' into 30 slices. The result shows that 5 out of 30 slices match the query.

I agree that each dataset should be indexed separately. Hopefully, Spike and I can work out a script 
for index automation in a short time.

@Spike-Wang @marirsg2 @ameliagalgon @qinxi117
